### ISSUE TITLE
Icon Component overhead

### ISSUE THREAD

**Issue by RyanYANG52** [antfu/unplugin-icons#109]
I will try explain using Svelte as an example, but it should be the same.

Currently import an an icon, unplugin-icons will generate an component on the fly, like this 

```js
import IconComponent from '~icons/collection/name
```
 to this IconComponent.svelte
```svelte
<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" {...$$props}>{@html `<path d="xxx" />`}</svg>
```
when bundling, it will compile to this for every component

```js
function nt(t) {
	let e,
		n =
			'<path d="xxx"/>',
		r = [
			{ viewBox: '0 0 24 24' },
			{ fill: 'none' },
			{ xmlns: 'http://www.w3.org/2000/svg' },
			t[0],
		],
		s = {};
	for (let o = 0; o < r.length; o += 1) s = d(s, r[o]);
	return {
		c() {
			(e = V('svg')), _(e, s);
		},
		m(o, c) {
			A(o, e, c), (e.innerHTML = n);
		},
		p(o, [c]) {
			_(
				e,
				(s = P(r, [
					{ viewBox: '0 0 24 24' },
					{ fill: 'none' },
					{ xmlns: 'http://www.w3.org/2000/svg' },
					c & 1 && o[0],
				]))
			);
		},
		i: f,
		o: f,
		d(o) {
			o && k(e);
		},
	};
}
```
this is what I use for my projects to minify overhead and without losing reactivity (not 100% sure I'm right though)

A shared Icon component

```svelte
<script>
    export let icon;
</script>

<svg xmlns="http://www.w3.org/2000/svg" {...icon.props} {...$$restProps}>
    {@html icon.path}
</svg>
```

and compile svg string to obj like this
```js
export default {
    path: `<path d="xxx" />`,
    props: {
         fill: 'none',
         viewBox: '0 0 24 24',
    }
}
```
use it like this
```svelte
<Icon icon={checked? icon1: icon2} height={size} width={size} on:click={onClick}/>
```

I think this way will save some code size, and keep reactivity, ssr should be ok too.

I know this way it may go against the main purpose of this project, use icon as Component, but maybe it can be an option

- add object Compiler, svg to icon object
- auto generate shared Icon component `~icons/component/svelte`
- maybe auto importing can work too, not sure

**Comment by RyanYANG52** [comment]
on second thought, this may only apply to svelte, solidjs, marko, compile language, not familiar with the others.

**Comment by dominikg** [comment]
This is very svelte specific and requires a custom svelte icon compiler.

You have to import the `<Icon>` component you mentioned avove from an alias or virtual id (relative paths would not work)
You need to extraxt the attributes and content separately from the `<svg>` source to be able to bind them into the imported `Icon`. 

Rather than providing that in unplugin-icons itself, i think a generic custom compiler option with importable third party compilers would be better for this case.

Regarding svelte there are other optimization options too eg. not using ...restProps but only binding style/class and the immutable compiler option which both result in even better runtime performance but should only be used if the limitations that come along with these work out. Again something a custom icon compiler could handle. I'll try to draft sth

**Comment by RyanYANG52** [comment]
Yes, I agree, custom compiler is the better approach.
Another small thing, to allow fully customize, right now scale option (width, height attr) can not be omitted(has to delete by custom compiler), and will always use `em` unit, I don't know if that is by design, I know it can be override by class or style, just think maybe it can be more flexible.
