### ISSUE TITLE
import certain icons causes invalid escape charactor added

### ISSUE THREAD

**Issue by u007** [antfu/unplugin-icons#143]
```
import { RightOutlined, LeftOutlined, UserOutlined } from '@ant-design/icons-vue';
```

LeftOutlined, UserOutlined works fine, but RightOutlined generatted this in componets.d.ts

```
RightOutlined: typeof import('~icons/ri/ght-outlined')['default']
```

pnpm lock file:
```
@ant-design/icons-vue/6.0.1_vue@3.2.26:
    resolution: {integrity: sha512-HigIgEVV6bbcrz2A92/qDzi/aKWB5EC6b6E1mxMB6aQA7ksiKY+gi4U94TpqyEIIhR23uaDrjufJ+xCZQ+vx6Q==}
    peerDependencies:
      vue: '>=3.0.3'
```

using template from https://github.com/antfu/vitesse

**Comment by userquin** [comment]
@u007 created project from vitesse template, adding `@ant-design/icons-vue` and using these 3 icons and works (the repo here https://github.com/userquin/vitesse-ant-design-icons-test):

![imagen](https://user-images.githubusercontent.com/6311119/147667950-77d1e1e4-6178-401d-84e7-ffc78454a59f.png)

![imagen](https://user-images.githubusercontent.com/6311119/147668002-271e9095-783a-4804-84be-8b8df142da2a.png)

Maybe this is related to `unplugin-vue-components`, this plugin doesn't generate any `dts` file. You should add on your `vitesse` based project a prefix on `unplugin-vue-components` for `unplugin-icons` resolver, since your are using icon from 2 sources, from this plugin and `ant design icons` (there is a `ri` collection on `@iconify`).

Can you test it adding for example `i-` prefix just to check this is the problem (you must add `i-` prefix to all `unplugin-icons`)?:

```ts
      // custom resolvers
      resolvers: [
        // auto import icons
        // https://github.com/antfu/unplugin-icons
        IconsResolver({
          componentPrefix: 'i-', // <== ADD A PREFIX
          // enabledCollections: ['carbon']
        }),
      ],

**Comment by u007** [comment]
hmm not sure what happened, it works now without the prefix set
